= OSGi Notes
From OSGi in Action - 2011
:toc:

== Chapter1: Why use OSGi?

It is used to address the lack of modularity in the Java platform.

Referred to as _SOA in a VM_.

=== What is modularity?
Code is separated into logical parts that have their own roles.

=== Java's limitations
==== Access Modifier
Java's access modifiers are good for low-level object-oriented aspects but does
not cater for modules.

Java uses a package to partition code, however for a code to be visible from one
package to another, it has to be defined as _public_. This makes those packages
also available to _everyone_. This will expose implementation details, and make
future refactorings harder as users may tend to rely on nonpublic API.

You could fix it by putting unrelated classes together in the same package, but
you'll break the logical structure of your application.

==== Classpath
The Java classpath does not pay any attention to code versions - it uses the
first version it finds.

Classpath hell:: More than one Jar file provides a given set of classes

You might suffer from `NoSuchMethodError` when a class from one Jar file uses a
class with a different version from what it was expecting.

In large application, it isn't uncommon to have dependencies on different
versions of the same component.

==== Deployment and Management
There is no easy way to evolve your application and its components after
deployment. (e.g dynamic plugin mechanism)

=== Overview of OSGi
* OSGi framework
* OSGi standard services

The framework is the runtime and implements the OSGI functionality.
The services define APIs for common tasks, such as logging and preferences.

=== OSGi layers
* Module layer
+
Concerned with packaging
* Lifecycle layer
+
Providing module management and access to the OSGi framewrk
* Service layer
+
Interaction and communication among modules


==== Module layers
Bundle:: Jar file with extra metadata. A bundle is also the OSGi module concept.

A bundle will contains all the typical stuff you will expect in a jar file
(class files and resources). Bundles are logical modules that combine to form a
given application. Bundles can declare which packages should be visible to other
bundles. So we don't suffer anymore from the problem of access modifiers and
different packages.

You can also declare which external packages the bundles depend on.

Advantage of doing this is that the OSGi framework can then manage the versions
by themselves; we avoid the classpath problem.

==== Lifecycle layer
This layer defines how the bundles are managed in the framework.

Bundle lifecycle::
* install
* update
* start
* stop
* uninstall

Lifecycle layer also defines how bundles gain access to their execution context.
The context allows the bundles to talk to the OSGi framework and use the
facilities it provides during execution.

==== Service layer
Service providers publish their services into a service registry, while service
clients search the registry to find available services to use.

The service layer promotes an interface-bsed development approach.

=== Putting all together
Metadata to add to `META-INF/MANIFEST.MF`:

----
Bundle-ManifestVersion: 2                       <1>
Bundle-Name: Greeting API                       <2>
Bundle-SymbolicName: org.foo.hello              <3>
Bundle-Version: 1.0                             <4>
Export-Package: org.foo.hello;version="1.0"     <5>
----
<1> OSGi metadata syntax version
<2> Human-readable Name
<3> Symbolic Name
<4> versions
<5> Important part: extends the functionality of a typical jar file so that you
can declare which packages in the jar are visible to its users. Only contents in
`org.foo.hello` are externally visible.

For other modules to define a dependency on another module:

----
[...]
Import-Package: org.foo.hello;version="[1.0, 2.0)"
----


==== Lifecycle example

[source,java]
----
public class Activator implements BundleActivator {
    public void start(BundleContext ctx) {
        // initialize
    }
    public void stop(BundleContext ctx) {
        // stop
    }
}
----

Since the framework uses the same activator instance while the bundle is active,
we can share variables between `start` and `stop`.

`BundleContext` allows us to get access to the OSGi framework.

To tell the framework about the bundle activator, you have to add this to your
manifest:

----
Bundle-Activator: org.foo.hello.Activator
Import-Package: org.osgi.framework              <1>
----
<1> We need this since the bundle activator has a dependency on it.


==== Service layer example
You could achieve this by writing an interface to your implementation. Then to
link the service (interface) to the implementation (or publish the service), in
your Activator, do this:

[source,java]
----
public class Activator implements BundleActivator {
    public void start(BundleContext ctx) {
        ctx.registerService(Greeting.class.getName(),
            new GreetingImpl("service"), null);
    }
}
----

To discover a service:

[source,java]
----
public class Client implements BundleActivator {
    public void start(BundleContext ctx) {
        ServiceReference ref =
        ctx.getServiceReference(Greeting.class.getName());      <1>

        ((Greeting) ctx.getService(ref)).sayHello();            <2>
    }
}
----
<1> Get an indirect reference from service registry
<2> Indirect reference used to access object instance.

This is done (use indirect reference) since services may be unregistered
dynamically. Holding a direct reference will prevent garbage collection of
uninstalled bundles.


== Chapter2: Modularity
The module layer is the foundation on which everything else rests in the OSGi
world.

=== Modularity and Object Orientation
Modules encapsulate classes, allowing you to express the logical relationship
among the classes.

Logical Modularity:: Code visibility
Physical Modularity:: How code is packaged

In OSGi, a logical module is referred to as a bundle, and so is the physical
module (jar).


=== OSGi Human Readable metadata
----
Bundle-Name: haha
Bundle-Description: boo
Bundle-DocURL: here
Bundle-Category: example, library
Bundle-Vendor: boo
Bundle-ContactAddress: 1212
Bundle-Copyright: OSGi
----

=== Bundle identification
`Bundle-SymbolicName` and `Bundle-Version` are intended for the OSGi framework
to help uniquely identify a bundle.

==== Code visibility
Standard jar files typically fail as bundles since they were written under the
assumption of global type visibility.

Internal bundle class path:: code forming the Bundle

Exported internal code:: explicitly exposed code from bundle class path for
sharing

Imported external code:: External code on which the bundle class path code
depends

==== Bundle class path
Bundle class path is a list of locations to search for classes. Difference with
java class path is that the bundle class path refers to locations inside the
bundle Jar file.

When a bundle class needs another class in the same bundle, the bundle class
path of the containing bundle is searched to find the class (instead of all the
directories inside the jar)

----
Bundle-ClassPath: .,other-classes/,embedded.jar     <1>
----

<1> This tells the OSGi framework to search the bundle jar file, then in the
folder called `other-classes`, then, in the embedded jar in the bundle.

If you don't specify a value, the framework supplies a default value of period
(.) .

The bundle class path value of . ocrresponds to the internal search policy of
standard Jar files.


==== Export internal Code
Used for exposing the public API of the code contained in the Jar file.

Export-Package:: A comma-separated list of internal bundle packages to expose
for sharing with other bundles.


You can also attach attributes to exported packages. A given bundle can use
attributes to differentiate its exports from other bundles.

e.g
----
Export-Package: org.foo.shape; vendor="haha", org.foo.other; vendor="haha" <1>
Export-Package: org.foo.shape; org.foo.other; vendor="haha" <2>
----
<2> is the shorthand notation for <1>


----
Export-Package: org.foo.shape; version="2.0.0" <1>
----
<1> OSGi supports the notion of package versioning


==== Import external code
----
Import-Package: org.foo.shape,org.foo.shape.other
Import-Package: org.foo.shape; org.foo.shape.other; version="1.3.0"
Import-Package: org.foo.shape; org.foo.shape.other; version="[1.3.0,2.0.0]" <1>
----
<1> You can specify a range on the version!

=== Class-search order
When a bundle needs a class at execution time, framework searches for class in
this order:

* If package starts with `java`, ask the parent classloader.
* If the class is from a package imported by the bundle, framework asks for
exporting bundle for the class.
* The bundle classpath is searched for the class.

=== OSGi Dependency resolution
Resolving a bundle may cause the framework to resolve other bundles
transitively.

If two bundles export the same package (e.g javax.servlet), then the framework
will favor the highest matching version. What heppens if both bundles export the
same version, 2.4.0?

In this case, the framework chooses baased on the order in which they were
installed in the framework. Bundles installed ealier are given priority over
bundles installed later.

Note: If the servlet API v2.4.0 is already resolved, the framework will choose
it to resolve the web application's dependency, even though it isn't export hte
highest version. Done to maximize the potential for collaboration. Bundles can
only collaborate if they are using the same version of a shared code.

Class space:: set of packages visible to a bundle

e.g
----
|Tomcat(2.4.0)| <-- |Http client| --> |Http service| --> |Servlet API (2.3.0)|
----
Http Client requires servlet v2.4.0 whereas Http service requires servlet
v2.3.0.

The clas spaces of HTTP client and HTTP service aren't consistent; two different
versions of javax.servlet are reachable from both. At execution time, this
results in class cast exceptions when the HTTP service and client bundles interact.

Solution:
----
|Tomcat(2.4.0)| <-- |Http client| --> |Http service|  |Servlet API (2.3.0)|
    |                                       |
    |                                       |
    +----------<----------------------------+
----

Because only one version of javax.servlet is in use, the class spaces are now consistent.

==== Inter vs intra-bundle dependencies
`uses` directive:: directive used with exported packages. Value is a
comma-delimited list of packages exposed by the associated exported package.

----
Export-Package: org.osgi.service.http;
uses:="javax.servlet"; version="1.0.0"
Import-Package: javax.servlet; version="2.3.0"
----

This ensures that the importers of `org.osgi.service.http` also use the same
`javax.servlet` used by the HTTP service implementation.

This will then happen:
----
|Tomcat(2.4.0)| x (can't resolve) x |Http client| --> |Http service| --> |Servlet API (2.3.0)|
----

But then the framework tries to resolve the dependency:
----
|Tomcat(2.4.0)|  |Http client| --> |Http service| --> |Servlet API (2.3.0)|
                     |                                       |
                     |                                       |
                     +---------->----------------------------+
----

`uses` contraints overly constrains dependency resolution.


== Lifecycle
OSGi module layer makes sure that class loading happens in a consistent and
predictable way.


=== What is lifecycle management?
The lifecycle layer allows you to install, start, update, stop, and uninstall
different bundles externally.

The lifecycle layer also provides programmatic access to bundles so they can
internally modify their application's configuration at execution time.

In servlet development, the lifecycle of the web application is managed by the
servlet container.

=== OSGi bundle lifecycle
The OSGi lifecycle layer is how you use the bundles. The lifecycle layer relies
on APIs.

The framework doesn't allow an installed bundle to be used until its
dependencies (Import-Package) are satisfied.

To specify the lifecycle class:
----
Bundle-Activator: org.foo.shell.Activator
----

An activator is necessary if you're creating a bundle and wish to specifically
interact with the OSGi API orneed to perform custom initialization.

Bundles don't necessarily need to be started in order to do useful things.

==== Bundle Activator API
[source,java]
----
public interface BundleActivator {
    public void start(BundleContext context) throws Exception;
    public void stop(BundleContext context) throws Exception;
}
----

[source,java]
----
public class Activator implements BundleActivator {
    public void start(BundleContext context) {}
    public void stopt(BundleContext context) {}

}
----
. The activator instance on which start() is called is the same instance on
which the stop() is called
. After stop() is called, the activator instance is discarded.
. If the bundle is restarted, a new activator instance is created.

The activator methods shouldn't do much work. This allows the framework to carry
on managing other bundles.

==== Bundle Context
Methods in BundleContext interface can be divided into 2 categories:
* Deployment and lifecycle Management
* Bundle interaction via services

For deployment and lifecycle:
[source,java]
----
getProperty(key);
getBundle();
installBundle(location, input);
installBundle(location);
getBundles();
addBundleListener(listener);
removeBundleListener(listener);
addFrameworkListener(listener);
removeFrameworkListener(listener);
----

==== Bundle
For each installed bundle, the framework creates a Bundle object to logically
represent it. Most lifecycle operations have a corresponding method in it.
